### ISSUE TITLE
Can't run homebridge when installed

### ISSUE THREAD

**Issue by nankiboy** [affix/homebridge-mcu-lamp#2]
I can't seem to run homebridge when I install some plugins (one's with dashes in the name e.g. mcu-lamp). Do you know why this may happen? 

Many thanks,
Tim

**Comment by davleo** [comment]
Same here
This is what I got: 
[2/10/2018, 9:57:43 PM] ====================
[2/10/2018, 9:57:43 PM] ERROR LOADING PLUGIN homebridge-mcu-lamp:
[2/10/2018, 9:57:43 PM] Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge-mcu-lamp/index.js:1:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[2/10/2018, 9:57:43 PM] ====================
[2/10/2018, 9:57:43 PM] No plugins found. See the README for information on installing plugins.
[2/10/2018, 9:57:43 PM] Loaded config.json with 1 accessories and 0 platforms.
[2/10/2018, 9:57:43 PM] ---
[2/10/2018, 9:57:43 PM] Loading 1 accessories...
/opt/node/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'McuLamp' was not registered by any plugin.
    at API.accessory (/opt/node/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/opt/node/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/opt/node/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/opt/node/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by skyeperry1** [comment]
try
`sudo npm install -g request`

**Comment by affix** [comment]
Sorry for the late fix. this has been resolved in 0.0.5
