### ISSUE TITLE
The requested accessory 'ismartswitch' was not registered by any plugin

### ISSUE THREAD

**Issue by directhacker** [Affix/homebridge-mcu-lamp#5]
No matter what I try, I still get this:

throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");

      ^

Error: The requested accessory 'ismartswitch' was not registered by any plugin.

    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)

    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:264:42)

    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)

    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)

    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

    at Module._compile (module.js:570:32)

    at Object.Module._extensions..js (module.js:579:10)

    at Module.load (module.js:487:32)

    at tryModuleLoad (module.js:446:12)

    at Function.Module._load (module.js:438:3)

    at Module.runMain (module.js:604:10)

    at run (bootstrap_node.js:393:7)

    at startup (bootstrap_node.js:150:9)

    at bootstrap_node.js:508:3

p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Menlo; color: #000000; background-color: #ffffff}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Menlo; color: #000000; background-color: #ffffff; min-height: 13.0px}
span.s1 {font-variant-ligatures: no-common-ligatures}

**Comment by pierrejochem** [comment]
How have you installed the package?

**Comment by renanconsalter** [comment]
"Request" dependency is missing. Just run "sudo npm install -g request" and try to run homebridge again.

**Comment by directhacker** [comment]
@renanconsalter, thanks! I’ll try that.

**Comment by renanconsalter** [comment]
@directhacker It worked?
